on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build image
        run: |
          cd Assignment_String_Transformation && docker build .